version: '3.8'

services:
  vehicle-simulator:
    build: .
    container_name: vehicle-simulator
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
